### ISSUE TITLE
Códigos para antiguedad en categorías MLU6394 MLU1467 MLU1468  MLU6393  MLU1473  MLU1474

### ISSUE THREAD

**Issue by pardo-bsso** [mercadolibre/api#100]
Hola , estamos tratando de publicar en esas categorías.
Según la documentación en https://api.mercadolibre.com/categories/MLU1467/attributes

Para MLU1467-ANTIGUE toma valores como por ejemplo 24a36bb (cinco años), cuando en otras MLA1466-ANTIG-HASTA_10_ANOS. Aparte, ese valor depende de la categoría, no son lo mismo para MLU1467 que para MLU1473.

En los anuncios, por ejemplo, http://apartamento.mercadolibre.com.uy/MLU-430467451-alquiler-departamento-3-dormitorios-punta-del-este-_JM , la antiguedad aparece listada como id en lugar de un texto mas humano.

Para poder publicar este atributo es mandatorio. Estamos haciendo algo mal ? 

ping @lbertalot mientras espero la registración del foro.

**Comment by lbertalot** [comment]
lo chequeamos y te respondemos, para tus consultas envíalas a developers@mercadolibre.com

**Comment by pardo-bsso** [comment]
>
> lo chequeamos y te respondemos, para tus consultas envíalas a developers@mercadolibre.com



Gracias!

**Comment by lbertalot** [comment]
Estas usando 
{           "id": "MLU1474-ANTIGUE",
            "value_name": "ecd66af"
        },

y deberías usar:
            "id": "MLU1474-ANTIGUE",
            "value_id": "ecd66af"
        },
