### ISSUE TITLE
Problemas con refresh token

### ISSUE THREAD

**Issue by mgg1976** [mercadolibre/api#101]
El refresh token me tira una excepción por status 400. Qué está pasando? Estoy usando el SDK de python y jamás tuve un problema parecido.

**Comment by fsolari** [comment]
Hola mgg1976, ¿Podrias enviarnos un mail a developers@mercadolibre con más
datos para entender el problema? ¿De qué manera estás realizando el
request? ¿Cuál es tu app_id? ¿Sucede con el refresh token de un usuario en
específico o todos? Si es un solo usuario, ¿Cuál?
Gracias.

Saludos,

El 23 de noviembre de 2015, 12:39, mgg1976 <notifications@github.com>
escribió:

> El refresh token me tira una excepción por status 400. Qué está pasando?
> Estoy usando el SDK de python y jamás tuve un problema parecido.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mercadolibre/api/issues/101>.
>



-- 
*Florencia Solari*
MercadoLibre Open Platform team
Av. La Voz del Interior 7000, Córdoba, Argentina
Int. 9835

**Comment by fsolari** [comment]
+ Developers

El 23 de noviembre de 2015, 12:41, Florencia Solari <
florencia.solari@mercadolibre.com> escribió:

> Hola mgg1976, ¿Podrias enviarnos un mail a developers@mercadolibre con
> más datos para entender el problema? ¿De qué manera estás realizando el
> request? ¿Cuál es tu app_id? ¿Sucede con el refresh token de un usuario en
> específico o todos? Si es un solo usuario, ¿Cuál?
> Gracias.
>
> Saludos,
>
> El 23 de noviembre de 2015, 12:39, mgg1976 <notifications@github.com>
> escribió:
>
>> El refresh token me tira una excepción por status 400. Qué está pasando?
>> Estoy usando el SDK de python y jamás tuve un problema parecido.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mercadolibre/api/issues/101>.
>>
>
>
>
> --
> *Florencia Solari*
> MercadoLibre Open Platform team
> Av. La Voz del Interior 7000, Córdoba, Argentina
> Int. 9835
>



-- 
*Florencia Solari*
MercadoLibre Open Platform team
Av. La Voz del Interior 7000, Córdoba, Argentina
Int. 9835

**Comment by mgg1976** [comment]
Te acabo de enviar un email

**Comment by fsolari** [comment]
Lo recibimos. Seguimos en esa cadena.

Saludos,

2015-11-23 13:10 GMT-03:00 mgg1976 <notifications@github.com>:

> Te acabo de enviar un email
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mercadolibre/api/issues/101#issuecomment-158981885>.
>



-- 
*Florencia Solari*
MercadoLibre Open Platform team
Av. La Voz del Interior 7000, Córdoba, Argentina
Int. 9835

**Comment by mgg1976** [comment]
Error mío. Solucionado
