### ISSUE TITLE
Visits API return wrong value

### ISSUE THREAD

**Issue by jjmalheiros** [mercadolibre/api#88]
The method   https://api.mercadolibre.com/users/{User_id}/items_visits?date_from={Date_from}&date_to={Date_to} return wrong value. Is returning outdated value. Can anyone help?

**Comment by fsolari** [comment]
Hi, could you give me an example, please?

**Comment by jjmalheiros** [comment]
![visitas](https://cloud.githubusercontent.com/assets/7660262/5741621/605ecda8-9bf3-11e4-843c-10f3040c2d3d.png)

searching for: https://api.mercadolibre.com/items/MLB616921634/visits?date_from=2014-01-01T00:00:00.000-03:00&date_to=2015-01-14T23:59:59.999-03:00

should return 91, but return 69.

**Comment by jjmalheiros** [comment]
Can anyone help?

**Comment by ricardoul** [comment]
Hello
Tthe issue is that you are getting the data from a different API 
The app to render that number  uses this is https://api.mercadolibre.com/visits/items?ids=MLB616921634, and not the one that you are using, the reason the both don´t have the same data, don´t know really, but I tested with a new item ,and both resolve the same data, maybe was a temporal issue who gets the data inconsistent.
Greets.
