### ISSUE TITLE
Put Shipping/Rastreamento - Custom mode

### ISSUE THREAD

**Issue by mendocs** [mercadolibre/api#93]
Estou precisando incluir os rastreamentos em meu app para um usuário que não usa MercadoEnvios
É possivel?

só recebo a mensagem: "Unauthorized receiver_id for order_id:..."

Já tentei os passos abaixo:

1)
Segui orientação desta pagina:
http://developers.mercadolibre.com/shipping-overview/

2) tentei um put na url da ordem:
https://api.mercadolibre.com/orders/{order_Id}/shipments?access_token=$ACCESS_TOKEN
retorno da API: {"message":"Unauthorized receiver_id for order_id: xxxxx","error":"invalid_user_id_for_order","status":401,"cause":null}

3)tentei um put nesta url:

https://api.mercadolibre.com/shipments/{shipment_Id}?access_token=$ACCESS_TOKEN
Retorno da API: 404 Not Found

obs:
No método GET em ambos url, consigo retornar a informação de rastreamento que inseri manualmente no detalhe da venda

No put envio as variaveis
string tracking_number	"PE114388115BR"	
string tracking_method	"Correios"	
string status	"shipped"	
string description	"PAC"	
string comments	"m_tracking_number"	
ou

curl -i -X PUT -H "Content-Type: application/json" -d 
'{
	tracking_number: "PE114388115BR"	
	tracking_method: "Correios"	
	status:	"shipped"	
	description : "PAC"	
	comments : "m_tracking_number"
}'

Consigo fazer put em perguntas, qualificaçao, notas de ordem, tudo menos rastreamento.

O usuário deu todas as pemissões: read, write e offline

Agradeço muito qualquer ajuda

**Comment by guibirow** [comment]
usa o fórum, lá tem sempre gente para responder e esta pergunta já foi respondida lá.
Abraços
