### ISSUE TITLE
body.invalid al intentar validar o listar item con .NET SDK

### ISSUE THREAD

**Issue by taeldany** [mercadolibre/api#94]
Este es el mensaje
"{\"message\":\"body.invalid\",\"error\":\"A body is expected. (B)\",\"status\":400,\"cause\":[]}"

Se usa el método Post de meli, y se agrega el body en format json

He intentado de todo y no logro publicar mi primer item, me está faltando algo?

Gracias

**Comment by lbertalot** [comment]
Hola Podrías ponerlo en el foro http://developers-forum.mercadolibre.com/ con el código que estas usando? 

Gracias

**Comment by taeldany** [comment]
Gracias, pero no me pude registrar, o sea nunca me llega el email de
validación, ya probé de todo, iguamente ya lo solucioné, estoy usando el
SDK de .NET

Muchas gracias
